name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t your-dockerhub-username/node-cicd-app .

    - name: Build and push Docker image
      run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/node-cicd-app:latest .
         docker push ${{ secrets.DOCKER_USERNAME }}/node-cicd-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/node-cicd-app:latest
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/node-cicd-app:latest
